### ISSUE TITLE
Include CQL Engine Information in CQL Test Runner Test Result

### ISSUE THREAD

**Issue by darkknight13** [cqframework/cql-tests-runner#13]
At present, the test result file generated by the CQL Test Runner doesn't have information regarding the specific CQL engine used for the tests. This proposal seeks to incorporate details about the CQL engine into the test results for better context and traceability.

**Comment by brynrhodes** [comment]
Add simple, user-entered information to be included in the Result:
* apiURL
* cqlVersion
* cqlTranslator
* cqlTranslatorVersion
* cqlEngine
* cqlEngineVersion
